# Generated by Django 4.0.5 on 2022-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='exprience',
            field=models.IntegerField(null=True),
        ),
    ]
