# Generated by Django 4.0.5 on 2022-06-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctor_exprience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assignedDoctorid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
